[package]
name = "axum-prometheus"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/Ptrskay3/axum-prometheus"
license = "MIT"
keywords = ["axum", "prometheus", "metrics"]
categories = ["asynchronous", "network-programming", "web-programming", "development-tools::profiling"]
repository = "hhttps://github.com/Ptrskay3/axum-prometheus"

# TODO: Make sure we need all of these deps.

[dependencies]
axum = "0.5.15"
futures = "0.3.23"
http = "0.2.8"
http-body = "0.4.5"
metrics = "0.20.1"
metrics-exporter-prometheus = "0.11.0"
pin-project = "1.0.12"
tower = "0.4.13"
tokio = { version = "1.20.1", features = ["rt-multi-thread", "macros"] }
